namespace: mitzidotcom
name: userinfo
version: 1.0.0
readme: README.md
authors:
- Mitesh The Mouse <mitsharm@redhat.com>
description: Configures three tier application
license:
- GPL-2.0-or-later
tags:
  - three_tier_app
dependencies: {}
repository: http://bastion.example.com:5050/mitzidotcom
documentation: http://bastion.example.com:5050/mitzidotcom/README.md
homepage: http://bastion.example.com
issues: http://example.com/issue/tracker
